# Generated by Django 5.0.1 on 2024-01-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
